### ISSUE TITLE
About the hack the box pwn challenge: nightmare

### ISSUE THREAD

**Issue by JOEJOE0619** [7Rocky/HackTheBox-scripts#1]
excuse me, I dot know how to display 0x7ffff7de1083 <__libc_start_main+243>: 0xb6e8c789 in the vmmap command after calling GDB. Could you tell how to set? thankyou :)

**Comment by 7Rocky** [comment]
Hi there,

Thanks for contacting me. Sorry, there was a typo, the last two lines should be swapped. What I did was take the address at position 13 in the stack and use “x 0x7ffff7ffc620” (there’s another typo in the address). That outputs "0x7ffff7de1083 <__libc_start_main+243>: 0xb6e8c789”. The “vmmap” command is independent, just to show the three types of addresses (binary, Glibc, stack).

Thanks for reading my blog. I’m glad you find it useful.

Best regards,

Rocky
